<?php

namespace AppBundle\Repository;

/**
 * BackscratcherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackscratcherRepository extends \Doctrine\ORM\EntityRepository
{
}
